### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by cauerego** [GaetanoPiazzolla/git-search#1]
sadly.

i'm still trying to find a good search solution!

**Comment by GaetanoPiazzolla** [comment]
I'm sorry to ear that. 
If you can provide me with some information about the error maybe I can fix it for you.

**Comment by cauerego** [comment]
well... it's all in italian so i don't know even where to begin! 🤣

really, just wanted to give you a heads up and kudos for trying to fix this hairy issue...

i would still love to get it fixed, though https://stackoverflow.com/questions/64810208/search-both-history-log-and-files-on-git-with-termux-and-regexp/274502

**Comment by GaetanoPiazzolla** [comment]
This project Is a UI built around Git grep command, but It searches in all branches of specified projects. 

Check here the alias for Git search: maybe It can help you. 
https://link.medium.com/6Bm23kchnbb

**Comment by cauerego** [comment]
sounds great! but i'm not even using branches (although i probably should). just needed to search the log. 😁

plus, it still doesn't work on my termux. i mean, it does bring up to 2 results in a great fashion, but then it literally crashes in halt. i can only terminate the whole termux process after just less than 1 second running it.

perhaps i'll manage to tweak it for my needs... we'll see. 😏

anyway, thanks!

this was kind of a non-issue from the beginning...

ps: i'll copy the relevant part here in case it helps someone who might be unable to see the article:

<blockquote>
The second (and best) way is to edit the file named `.gitconfig` that should be present in your home directory adding a new section named `[alias]` if not already present.

```
[user]
 name = gpiazzolla
 email = gae.piaz@gmail.com
[alias]
  {aliasName} = {command}
```

# The Aliases
Search every branch for a given reg-exp
`search = ! git branch -a | sed '/->/d' | sed 's/\\*//' | xargs git grep -n -I`
This AWESOME command searches in every local and remote branch for a given text. The first TOKEN is the name of the branch, the second is the FILE where the regex has found a match, the third is the content with the colored text. In the next image there is the ouput of the command `git search fixes` I’ve run on spring-security repository.
</blockquote>
